# Generated by Django 4.2.7 on 2025-08-11 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("is_deadline", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Event Type",
                "verbose_name_plural": "Event Types",
            },
        ),
        migrations.AlterModelOptions(
            name="caseevent",
            options={"ordering": ["starts_at"]},
        ),
        migrations.RenameField(
            model_name="caseevent",
            old_name="notes",
            new_name="description",
        ),
        migrations.AddField(
            model_name="caseevent",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="events_attending", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="is_all_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="reminder_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="caseevent",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="caseevent",
            index=models.Index(
                fields=["starts_at"], name="cases_casee_starts__7188ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseevent",
            index=models.Index(
                fields=["case", "starts_at"], name="cases_casee_case_id_56d3e4_idx"
            ),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cases.eventtype",
            ),
        ),
    ]
