# Generated by Django 4.2.7 on 2025-08-14 12:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_casedocument_description_casedocument_download_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancedInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numri i Faturës"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data e Lëshimit",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data e Scadencës")),
                (
                    "subtotal_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subtotal_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Dërguar"),
                            ("paid", "Paguar"),
                            ("overdue", "Vonuar"),
                            ("cancelled", "Anuluar"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Shënime")),
                ("is_auto_generated", models.BooleanField(default=False)),
                ("auto_send", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advanced_invoices",
                        to="cases.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.client"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura e Avancuar",
                "verbose_name_plural": "Faturat e Avancuara",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="ClientMessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="client_messages/attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Kodi i Valutës"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Emri")),
                ("symbol", models.CharField(max_length=5, verbose_name="Simboli")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Kursi i Këmbimit",
                    ),
                ),
                (
                    "is_base_currency",
                    models.BooleanField(default=False, verbose_name="Valuta Bazë"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktive")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Valuta",
                "verbose_name_plural": "Valutat",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Emri"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Përshkrimi"),
                ),
                (
                    "is_billable",
                    models.BooleanField(default=True, verbose_name="E Faturueshme"),
                ),
                (
                    "default_markup_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Përqindja e Markup-it Default",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Kategoria e Shpenzimeve",
                "verbose_name_plural": "Kategoritë e Shpenzimeve",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "billable_hours_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "expense_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_invoiced",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "collection_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("average_collection_time", models.PositiveIntegerField(default=0)),
                ("active_cases_count", models.PositiveIntegerField(default=0)),
                ("new_cases_count", models.PositiveIntegerField(default=0)),
                ("closed_cases_count", models.PositiveIntegerField(default=0)),
                (
                    "total_billable_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "average_hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "billable_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Metrikat Financiare",
                "verbose_name_plural": "Metrikat Financiare",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Emri")),
                ("html_template", models.TextField(verbose_name="Template HTML")),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Template Fature",
                "verbose_name_plural": "Template Faturash",
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Emri")),
                ("description", models.TextField(verbose_name="Përshkrimi")),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("financial", "Financiare"),
                            ("operational", "Operacionale"),
                            ("client", "Klienti"),
                            ("efficiency", "Efikasiteti"),
                            ("growth", "Rritja"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("unit", models.CharField(default="number", max_length=20)),
                ("format_string", models.CharField(default="{value}", max_length=50)),
                ("trend_direction", models.CharField(default="up", max_length=10)),
                (
                    "percentage_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "calculation_method",
                    models.TextField(verbose_name="Metoda e Llogaritjes"),
                ),
                ("update_frequency", models.CharField(default="daily", max_length=20)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPI-të",
                "ordering": ["kpi_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="RevenueForecasting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Mujore"),
                            ("quarterly", "Tremujore"),
                            ("yearly", "Vjetore"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "forecast_period",
                    models.DateField(verbose_name="Periudha e Parashikuar"),
                ),
                (
                    "projected_revenue",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "projected_billable_hours",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("projected_new_cases", models.PositiveIntegerField()),
                (
                    "confidence_level",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "methodology",
                    models.CharField(max_length=100, verbose_name="Metodologjia"),
                ),
                (
                    "assumptions",
                    models.JSONField(default=dict, verbose_name="Supozimet"),
                ),
                ("historical_data_start", models.DateField()),
                ("historical_data_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parashikimi i të Ardhurave",
                "verbose_name_plural": "Parashikimet e të Ardhurave",
                "ordering": ["-forecast_period"],
                "unique_together": {("forecast_type", "forecast_period")},
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Javore"),
                            ("monthly", "Mujore"),
                            ("quarterly", "Tremujore"),
                            ("yearly", "Vjetore"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("next_invoice_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_invoices",
                        to="cases.case",
                    ),
                ),
                (
                    "template_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.advancedinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura Periodike",
                "verbose_name_plural": "Faturat Periodike",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Transfer Bankar"),
                            ("credit_card", "Kartë Krediti"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("check", "Çek"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Në Pritje"),
                            ("completed", "Përfunduar"),
                            ("failed", "Dështuar"),
                            ("refunded", "Rimbursuar"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.currency"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="cases.advancedinvoice",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagesa",
                "verbose_name_plural": "Pagesat",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Përshkrimi"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sasia"
                    ),
                ),
                (
                    "markup_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "billable_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="expenses/receipts/"
                    ),
                ),
                ("is_billable", models.BooleanField(default=True)),
                ("is_billed", models.BooleanField(default=False)),
                ("expense_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="cases.case",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.expensecategory",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.currency"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Regjistruar nga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shpenzimi",
                "verbose_name_plural": "Shpenzimet",
                "ordering": ["-expense_date"],
            },
        ),
        migrations.CreateModel(
            name="ClientSatisfactionMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_satisfaction", models.PositiveIntegerField()),
                ("communication_rating", models.PositiveIntegerField()),
                ("quality_rating", models.PositiveIntegerField()),
                ("timeliness_rating", models.PositiveIntegerField()),
                ("value_rating", models.PositiveIntegerField()),
                ("nps_score", models.IntegerField(blank=True, null=True)),
                ("would_recommend", models.BooleanField(null=True)),
                ("positive_aspects", models.JSONField(blank=True, default=list)),
                ("improvement_areas", models.JSONField(blank=True, default=list)),
                ("survey_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satisfaction_metrics",
                        to="cases.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metritat e Kënaqësisë së Klientit",
                "verbose_name_plural": "Metritat e Kënaqësisë së Klientëve",
                "ordering": ["-survey_date"],
            },
        ),
        migrations.CreateModel(
            name="ClientPortalAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Portal i Aktivizuar"
                    ),
                ),
                (
                    "can_view_documents",
                    models.BooleanField(
                        default=True, verbose_name="Mund të shikojë dokumente"
                    ),
                ),
                (
                    "can_download_documents",
                    models.BooleanField(
                        default=True, verbose_name="Mund të shkarkojë dokumente"
                    ),
                ),
                (
                    "can_view_invoices",
                    models.BooleanField(
                        default=True, verbose_name="Mund të shikojë faturat"
                    ),
                ),
                (
                    "can_view_payments",
                    models.BooleanField(
                        default=True, verbose_name="Mund të shikojë pagesat"
                    ),
                ),
                (
                    "can_upload_documents",
                    models.BooleanField(
                        default=False, verbose_name="Mund të ngarkojë dokumente"
                    ),
                ),
                (
                    "can_message_lawyer",
                    models.BooleanField(
                        default=True, verbose_name="Mund të dërgojë mesazhe"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Njoftimet via Email"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Njoftimet via SMS"
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_access",
                        to="cases.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aksesi në Portal të Klientit",
                "verbose_name_plural": "Aksesets në Portal të Klientëve",
            },
        ),
        migrations.CreateModel(
            name="ClientNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("case_update", "Përditësim Rasti"),
                            ("document_shared", "Dokument i Ndarë"),
                            ("invoice_issued", "Faturë e Lëshuar"),
                            ("payment_received", "Pagesë e Marrë"),
                            ("appointment_scheduled", "Takim i Planifikuar"),
                            ("deadline_reminder", "Kujtues për Afatin"),
                            ("message_received", "Mesazh i Marrë"),
                            ("system", "Sistemi"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titulli")),
                ("message", models.TextField(verbose_name="Mesazhi")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="URL e Veprimit"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "E palexuar"),
                            ("read", "E lexuar"),
                            ("archived", "E arkivuar"),
                        ],
                        default="unread",
                        max_length=20,
                    ),
                ),
                ("sent_via_email", models.BooleanField(default=False)),
                ("sent_via_sms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="cases.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Njoftimi i Klientit",
                "verbose_name_plural": "Njoftimet e Klientëve",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("client_to_lawyer", "Klient → Avokat"),
                            ("lawyer_to_client", "Avokat → Klient"),
                            ("system", "Sistemi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subjekti")),
                ("content", models.TextField(verbose_name="Përmbajtja")),
                ("is_read", models.BooleanField(default=False)),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="Urgjent"),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True, to="cases.clientmessageattachment"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_messages",
                        to="cases.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.client"
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="cases.clientmessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dërguesi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesazhi i Klientit",
                "verbose_name_plural": "Mesazhet e Klientëve",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 - Shumë i dobët"),
                            (2, "2 - I dobët"),
                            (3, "3 - Mesatar"),
                            (4, "4 - I mirë"),
                            (5, "5 - Shumë i mirë"),
                        ],
                        verbose_name="Vlerësimi i Përgjithshëm",
                    ),
                ),
                (
                    "communication_rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 - Shumë i dobët"),
                            (2, "2 - I dobët"),
                            (3, "3 - Mesatar"),
                            (4, "4 - I mirë"),
                            (5, "5 - Shumë i mirë"),
                        ],
                        verbose_name="Komunikimi",
                    ),
                ),
                (
                    "service_quality_rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 - Shumë i dobët"),
                            (2, "2 - I dobët"),
                            (3, "3 - Mesatar"),
                            (4, "4 - I mirë"),
                            (5, "5 - Shumë i mirë"),
                        ],
                        verbose_name="Cilësia e Shërbimit",
                    ),
                ),
                (
                    "timeliness_rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 - Shumë i dobët"),
                            (2, "2 - I dobët"),
                            (3, "3 - Mesatar"),
                            (4, "4 - I mirë"),
                            (5, "5 - Shumë i mirë"),
                        ],
                        verbose_name="Përpikëria",
                    ),
                ),
                (
                    "positive_feedback",
                    models.TextField(blank=True, verbose_name="Aspektet Pozitive"),
                ),
                (
                    "improvement_suggestions",
                    models.TextField(
                        blank=True, verbose_name="Sugjerime për Përmirësim"
                    ),
                ),
                (
                    "additional_comments",
                    models.TextField(blank=True, verbose_name="Komente Shtesë"),
                ),
                (
                    "would_recommend",
                    models.BooleanField(null=True, verbose_name="Do ta rekomandonte"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Anonim"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="cases.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback-u i Klientit",
                "verbose_name_plural": "Feedback-et e Klientëve",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseOutcomeMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("won", "Fituar"),
                            ("lost", "Humbur"),
                            ("settled", "Marrëveshje"),
                            ("dismissed", "Hedhur poshtë"),
                            ("ongoing", "Në vijim"),
                            ("withdrawn", "Tërhequr"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("outcome_date", models.DateField(blank=True, null=True)),
                (
                    "amount_claimed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "amount_awarded",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "settlement_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_duration_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "time_to_resolution_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_legal_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "client_satisfaction_score",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "success_rate_factor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome_metrics",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metritat e Rezultatit të Rastit",
                "verbose_name_plural": "Metritat e Rezultateve të Rasteve",
            },
        ),
        migrations.CreateModel(
            name="BillingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Emri i Tarifës"),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Tarife Orare"),
                            ("fixed", "Tarife Fikse"),
                            ("contingency", "Përqindje nga Rezultati"),
                        ],
                        max_length=20,
                        verbose_name="Lloji i Tarifës",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sasia"
                    ),
                ),
                (
                    "case_category",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Kategoria e Rastit",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.currency",
                        verbose_name="Valuta",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa e Faturimit",
                "verbose_name_plural": "Tarifat e Faturimit",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Emri i Raportit"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("financial", "Raporti Financiar"),
                            ("performance", "Performancë"),
                            ("productivity", "Produktiviteti"),
                            ("client_satisfaction", "Kënaqësia e Klientit"),
                            ("case_outcome", "Rezultatet e Rasteve"),
                            ("time_utilization", "Përdorimi i Kohës"),
                            ("revenue_forecast", "Parashikimi i të Ardhurave"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Ditore"),
                            ("weekly", "Javore"),
                            ("monthly", "Mujore"),
                            ("quarterly", "Tremujore"),
                            ("yearly", "Vjetore"),
                            ("custom", "E Personalizuar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Filtrat"),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parametrat"
                    ),
                ),
                ("report_data", models.JSONField(verbose_name="Të Dhënat e Raportit")),
                (
                    "summary_data",
                    models.JSONField(default=dict, verbose_name="Përmbledhja"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="I Planifikuar"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Raporti Analitik",
                "verbose_name_plural": "Raportet Analitike",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddField(
            model_name="advancedinvoice",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cases.currency"
            ),
        ),
        migrations.CreateModel(
            name="UserPerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_hours_logged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "billable_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "non_billable_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "utilization_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("active_cases_count", models.PositiveIntegerField(default=0)),
                ("cases_opened", models.PositiveIntegerField(default=0)),
                ("cases_closed", models.PositiveIntegerField(default=0)),
                ("client_meetings", models.PositiveIntegerField(default=0)),
                ("documents_created", models.PositiveIntegerField(default=0)),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("deadlines_met", models.PositiveIntegerField(default=0)),
                ("deadlines_missed", models.PositiveIntegerField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Metritat e Performancës së Përdoruesit",
                "verbose_name_plural": "Metritat e Performancës së Përdoruesve",
                "ordering": ["-date", "user"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="TimeUtilizationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_work_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "billable_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "non_billable_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "case_work_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "admin_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "meeting_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "research_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("client_breakdown", models.JSONField(blank=True, default=dict)),
                ("case_breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "utilization_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "efficiency_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Raporti i Përdorimit të Kohës",
                "verbose_name_plural": "Raportet e Përdorimit të Kohës",
                "ordering": ["-report_date"],
                "unique_together": {("user", "report_date")},
            },
        ),
        migrations.CreateModel(
            name="InvoiceTimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.DecimalField(decimal_places=2, max_digits=8)),
                ("rate_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "billing_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.billingrate",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="cases.advancedinvoice",
                    ),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.timeentry",
                    ),
                ),
            ],
            options={
                "unique_together": {("invoice", "time_entry")},
            },
        ),
        migrations.CreateModel(
            name="InvoiceExpenseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billable_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.expense"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_items",
                        to="cases.advancedinvoice",
                    ),
                ),
            ],
            options={
                "unique_together": {("invoice", "expense")},
            },
        ),
        migrations.CreateModel(
            name="ClientPaymentTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_enabled", models.BooleanField(default=True)),
                (
                    "auto_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Kujtuesa Automatike"
                    ),
                ),
                ("reminder_days_before_due", models.PositiveIntegerField(default=7)),
                ("reminder_days_after_due", models.PositiveIntegerField(default=3)),
                ("max_reminders", models.PositiveIntegerField(default=5)),
                ("reminders_sent", models.PositiveIntegerField(default=0)),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_tracking",
                        to="cases.client",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.advancedinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gjurmimi i Pagesave të Klientit",
                "verbose_name_plural": "Gjurmimet e Pagesave të Klientëve",
                "unique_together": {("client", "invoice")},
            },
        ),
        migrations.CreateModel(
            name="ClientDocumentShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("view_only", "Vetëm Shikimi"),
                            ("download", "Shkarkim i Lejuar"),
                            ("comment", "Me Komente"),
                        ],
                        default="view_only",
                        max_length=20,
                    ),
                ),
                ("access_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Skadon më"
                    ),
                ),
                (
                    "max_downloads",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Shkarkime Maksimale"
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                (
                    "share_message",
                    models.TextField(blank=True, verbose_name="Mesazhi i Ndarjes"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.case"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.client"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_shares",
                        to="cases.casedocument",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ndarë nga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ndarje Dokumenti me Klient",
                "verbose_name_plural": "Ndarjet e Dokumenteve me Klientët",
                "ordering": ["-shared_at"],
                "unique_together": {("document", "client")},
            },
        ),
        migrations.CreateModel(
            name="ClientDashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("case_status", "Statusi i Rastit"),
                            ("recent_documents", "Dokumente të Fundit"),
                            ("upcoming_events", "Ngjarje të Ardhshme"),
                            ("invoices_summary", "Përmbledhje Faturash"),
                            ("payments_summary", "Përmbledhje Pagesash"),
                            ("messages", "Mesazhet"),
                            ("notifications", "Njoftimet"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Pozicioni"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="I Dukshëm"),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to="cases.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget i Dashboard-it të Klientit",
                "verbose_name_plural": "Widget-et e Dashboard-it të Klientëve",
                "ordering": ["client", "position"],
                "unique_together": {("client", "widget_type")},
            },
        ),
    ]
