# Generated by Django 4.2.7 on 2025-08-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_advancedinvoice_clientmessageattachment_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancedinvoice",
            name="description",
            field=models.TextField(blank=True, verbose_name="Përshkrimi"),
        ),
        migrations.AddField(
            model_name="advancedinvoice",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("net_15", "Net 15 days"),
                    ("net_30", "Net 30 days"),
                    ("net_60", "Net 60 days"),
                    ("due_on_receipt", "Due on receipt"),
                ],
                default="net_30",
                max_length=20,
                verbose_name="Kushtet e Pagesës",
            ),
        ),
    ]
